#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon --start --quiet --exec $DAEMON -- -d
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon --stop --quiet --signal TERM --name $DAEMON_NAME
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
